### PR TITLE
Fix authoritative source desc

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by philips** [comment]
The details of what this authoritative_source stuff mean should be in the spec not in the commit messages as they are now.

**Comment by ghost** [comment]
Isn't it? This commit message merely adds details for the motivation - the current SPEC does not appear to do that on any other field.

**Comment by philips** [comment]
We probably should start documenting the motivation for some of these fields as they are getting pretty abstract.

**Comment by rhatdan** [comment]
Yes I agree, perhaps we should reformat or have a additional info at the bottom describing the intention of each object.

**Comment by philips** [comment]
Yes but we should start adding motivations to the spec for the new people

**Pull request closed without merging**
