### PR TITLE
Allow optional dash between PRODUCT and $PRODUCTGEN

### PR DESCRIPTION
**Pull request by pbabinca**
This formalizes the naming policy that can be seen in the wild already.

### CODE REVIEW

**Comment by pbabinca** [comment]
//cc @ssampat

**Comment by ssampat** [comment]
Thanks, Pavol! You probably missed out this one - https://github.com/projectatomic/ContainerApplicationGenericLabels/pull/86/commits/f8e36b9c3735c745bb4a5fae4e1819ff52e50222#diff-91ad106c9870dba967a0828e35335257R211 ?

**Comment by pbabinca** [comment]
Thanks, fixed: https://github.com/projectatomic/ContainerApplicationGenericLabels/pull/86/files#diff-91ad106c9870dba967a0828e35335257R75

**Comment by ssampat** [comment]
Thanks!

**Comment by pbabinca** [comment]
@ssampat who can review and merge this?

**Comment by ssampat** [comment]
@aweiteka @julienlim @rhatdan can you take a look?

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
