### PR TITLE
add sigstore labels

### PR DESCRIPTION
**Pull request by aweiteka**
@rhatdan please review

### CODE REVIEW

**Comment by rhatdan** [comment]
Could I have multiple signatures and signature stores?

**Comment by aweiteka** [comment]
> Could I have multiple signatures and signature stores?

Multiple signatures, yes. Not sure about multiple sigstores. In general people could push more than one of these using different tags.

**Comment by aweiteka** [comment]
@rhatdan I'd like to get this in so we can have a first pass out there. I'm happy to revisit the multi-sigstore/keys use case later.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
