### PR TITLE
Added fields used or proposed inside Red Hat:

### PR DESCRIPTION
**Pull request by ghost**
- AuthoritativeRegistry
  - Official registry for the image. E.g. registry.access.redhat.com for rhel7/rhel.
- DistScope
  - Field to track the intended scope of distribution for the image. Specifically to be used with the value "Exclusive" for images that can only be redistributed through the AuthoritativeRegistry. "Private" should be the default and trigger a warning when pushing, etc.
- Component
  - Bugtracking component for the image. E.g. used for BZ components in Red Hat images.

### CODE REVIEW

**Comment by jonboulle** [comment]
Peanut gallery, these seem awfully vendor specific for a generic spec; -1 on "Registry" in particular which is very much a Docker implementation detail.

**Comment by rhatdan** [comment]
@jonboulle if it was changed to OfficialSite or something like that, IE The source of the container image?

I think Daniel is trying to establish that if you get this container image from site other then foobar.example.com, then it is less then trusted.    But I guess we can ask Daniel to elaborate.

**Comment by ghost** [comment]
@rhatdan I will break them up into two different issues as AuthoritativeRegistry and DistributionScope are connected.

DistributionScope is different from License as there are other factors than the software license(s) of the included software or the aggregate work governing the distribution: In a company you might be building images from Free Software, but you still may treat them as private, non-redistributable. For a vendor like Red Hat, the stream of content is governed by the subscription agreement, and while redistribution would not be a violation of the license terms, it break the subscription agreement.
Another concern with the License field is, that we should define whether it applies to the content or the aggregate work of putting together the image. If it's the content, would you list all licenses or just "Multiple"? Is there value in listing the license of the aggregate work? Might be too thin to protect anyways.

**Comment by llunved** [comment]
@jonboulle I can see the rationale for that and I think we agree on a high level. Anyhow 'authoritative_source' or 'AuthoritativeSource' ok with you?

**Comment by rhatdan** [comment]
If we go with lowercase as in other pull request we can add authoritative_source.

**Comment by jonboulle** [comment]
I'd still question the utility of trying to standardise such a polymorphic field, but sure, `authoritative_source` is better

**Pull request closed without merging**
