### PR TITLE
README.md: Add authoritative_source and distribution_scope labels, ad…

### PR DESCRIPTION
**Pull request by ghost**
…d Details sections

Adding authoritative_source and distribution_scope labels to allow locating the original source of an image as well as encoding the intended scope of distribution.

Adding a section with details on the label fields to add context and discuss details.

### CODE REVIEW

**Comment by ghost** [comment]
Once this is merged, I will add details for other labels.

**Comment by rhatdan** [comment]
@riekrh squash your pulls.

git rebase -i origin
Take second patch and change pick to f
Save
git push riekrh --force

**Comment by ghost** [comment]
@rhatdan done

**Comment by ghost** [comment]
@jonboulle does this work for you?

**Comment by rhatdan** [comment]
No protests, so LGTM

**Pull request merged**
