### PR TITLE
Removing BuildHost

### PR DESCRIPTION
**Pull request by ghost**
In modern clustered build systems, BuildHost information is not really useful anymore and is better handled by the build system itself.

### CODE REVIEW

**Comment by cgwalters** [comment]
:+1:  on the change, but can you format your commit message to be a short subject, followed by the rationale as the body, instead of as one line?

See:
- https://wiki.openstack.org/wiki/GitCommitMessages
- https://wiki.gnome.org/GnomeLove/SubmittingPatches

etc.

**Comment by cgwalters** [comment]
https://github.com/projectatomic/ContainerApplicationGenericLabels/commit/69e37d12774eaa79053d9247d257b30e17a545b6 is a good example from this repo.

**Comment by cgwalters** [comment]
Changing the title in the PR doesn't change the git commit title.

**Comment by rhatdan** [comment]
Oh I thought it did.

**Comment by jonboulle** [comment]
:+1:

**Pull request merged**
