### PR TITLE
README: move everything to lower case

### PR DESCRIPTION
**Pull request by philips**
As discussed in #8 standardize the capitalization.

### CODE REVIEW

**Comment by rhatdan** [comment]
@riekrh Here is the pull request I was talking about.

If you agree to go to lower case and _ or - between mutli-words labels works for me.

I have changed atomic command to look for name, uppercase(name), Lowercase(name), Capatalized(name)

Changing capitalization will not break the command.

**Comment by llunved** [comment]
@rhatdan I suggest that we go to lowercase-underscore ('_') naming. E.g. "build_date".

**Comment by rhatdan** [comment]
@philips That ok with you?

**Comment by philips** [comment]
@rhatdan Yes, we loosened up the annotations key name in appc so this will work: https://github.com/appc/spec/pull/442

**Comment by rhatdan** [comment]
Modified to match new standard.

**Pull request closed without merging**
